name: Run pre-commit hooks

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Checks with pre-commit
        uses: pre-commit/action@v2.0.3
